- name: setup catalogue
  hosts: localhost
  become: yes
  tasks:
  - name: setup nodesource
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: install nodeJS
    ansible.builtin.yum:
     name: nodejs 
     state: installed

  - name: create roboshop user
    ansible.builtin.command: useradd roboshop
    register: out       

  - name: create app dir
    ansible.builtin.file: 
      path: /app
      state: directory
      mode: 0755

  - name: Download application code
    ansible.builtin.get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip 
      dest: /tmp/catalogue.zip
      
  - name: unarchive the code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: 
      
  - name: npm install packages
    ansible.builtin.yum:
      name: npm
      state: installed

  - name: copy catalogue service config
    ansible.builtin.copy:
    content: catalogue.service
    dest: vim /etc/systemd/system/catalogue.service
 
  - name: setup systemd service
    ansible.builtin.systemd_service: 
      name: daemon reload
      daemon_reload: true

  - name: start and enable service 
    ansible.builtin.systemd_service:
    name: catalogue
    state: started
    enabled: true    

  - name: copy mongo repo
    ansible.builtin.copy:
    content: mongo.repo
    dest: vim /etc/yum.repos.d/mongo.repo

  - name: install mongo client
    ansible.builtin.yum: 
      name: mongodb-org-shell 
      state: installed  

  - name: load schema
    ansible.builtin.shell: mongo --host MONGODB-SERVER-IPADDRESS </app/schema/catalogue.js    
        