- name: install nginx
  hosts: app # host name in the inventory file
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
      update_cache: yes  
 
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes