- name: MongoDB component
  hosts: mongodb
  become: yes
  tasks:
  - name: Setup MongoDB repo
    ansible.builtin.copy:
      src: mongodb-org.list
      dest: /etc/apt/sources.list.d/mongodb-org.list

  - name: Install MongoDB
    ansible.builtin.apt: 
      name: mongodb-org
      state: present
      update_cache: yes

  - name: Start and Enable MongoDB
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: Update MongoDB listen address
    ansible.builtin.replace:   
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Restart MongoDB
    ansible.builtin.service:
      name: mongod
      state: restarted

