- name: MongoDB component
  hosts: mongodb
  become: yes
  tasks:
  - name: Import MongoDB public GPG key
    ansible.builtin.apt_key:
      url: https://www.mongodb.org/static/pgp/server-7.0.asc
      state: present

  - name: Add MongoDB repository (force jammy for Ubuntu 24.04)
    ansible.builtin.apt_repository:
      repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse"
      state: present


  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Install MongoDB
    ansible.builtin.apt:
      name: mongodb-org
      state: present
      update_cache: yes

  - name: Start and Enable MongoDB
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: Update MongoDB listen address
    ansible.builtin.replace:   
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Restart MongoDB
    ansible.builtin.service:
      name: mongod
      state: restarted

